# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dylancoapolloserver
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-server2
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
build:
  esbuild: false
plugins:
  - serverless-plugin-typescript
  - serverless-offline
